import { useState, useRef, useEffect } from 'react';
import { generateImg } from '@sedaat/image-gen';

/**
 * Tooltip descriptions shown on tech-stack tag hover.
 * Falls back to the tech name itself if not listed.
 */
const TECH_DESCRIPTIONS = {
  ReactJS:        'UI library for building component-based interfaces',
  JavaScript:     'Scripting language for web interactivity',
  HTML:           'Markup language for structuring web pages',
  CSS:            'Stylesheet language for visual presentation',
  'Modular Scale':'Typographic scale tool for harmonious sizing',
  Vercel:         'Cloud platform for frontend deployments',
  NodeJS:         'JavaScript runtime for server-side code',
  ExpressJS:      'Minimal web framework for Node.js',
  PostgreSQL:     'Relational database with advanced features',
  'JWT Tokens':   'Compact tokens for stateless authentication',
  bcrypt:         'Password hashing library for secure storage',
  'Sequelize ORM':'Promise-based ORM for SQL databases',
};

/**
 * ProjectCard — mirrors the original plain-JS article structure.
 * Each card has a canvas thumbnail generated by generateImg.
 *
 * @param {{ id: number, title: string, description: string, techStack: string[], links: {name: string, url: string}[] }} props
 */
export default function ProjectCard({ title, description, techStack, links }) {
  const [expanded, setExpanded] = useState(false);
  const canvasRef = useRef(null);

  // Generate the per-card canvas thumbnail on mount
  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;

    canvas.width = 800;
    canvas.height = 400;
    generateImg(canvas);
  }, []);

  const isLong = description.length > 90;
  const truncated = isLong ? description.slice(0, 90) + '…' : description;

  return (
    <article className="project-card">
      <div className="image-container">
        <canvas
          ref={canvasRef}
          className="project-image"
          role="img"
          aria-label={`Generative art thumbnail for ${title}`}
        />
      </div>

      <div className="project-details">
        <h3 className="project-title">{title}</h3>

        <p className="project-description">
          {isLong && !expanded ? truncated : description}
        </p>

        {isLong && (
          <button
            className="more-btn"
            onClick={() => setExpanded(e => !e)}
            aria-expanded={expanded}
          >
            {expanded ? 'Show Less' : 'Read More'}
          </button>
        )}

        <ul className="project-links">
          {links.map((link) => (
            <li key={link.url}>
              <a
                href={link.url}
                target="_blank"
                rel="noopener noreferrer"
                className="project-link"
                title="Opens in new tab"
              >
                {link.name} ↗
              </a>
            </li>
          ))}
        </ul>

        <ul className="tech-stack">
          {techStack.map((tech) => (
            <li
              key={tech}
              className="tech-tag"
              data-tooltip={TECH_DESCRIPTIONS[tech] ?? tech}
            >
              {tech}
            </li>
          ))}
        </ul>
      </div>
    </article>
  );
}
